// CONSTANT VALUES

export const TYPES = {
    CURRENT_USER_FETCHING_INIT: 'CURRENT_USER_FETCHING_INIT',
    CURRENT_USER_FETCHED_FAILD: 'CURRENT_USER_FETCHED_FAILD',
    CURRENT_USER_FETCHED_SUCCESS: 'CURRENT_USER_FETCHED_SUCCESS',
    USER_FETCHING_BY_ID_INIT: 'USER_FETCHING_BY_ID_INIT',
    USER_FETCHED_BY_ID_FAILD: 'USER_FETCHED_BY_ID_FAILD',
    USER_FETCHED_BY_ID_SUCCESS: 'USER_FETCHED_BY_ID_SUCCESS',
    APP_IS_ONLINE: 'APP_IS_ONLINE',
    APP_IS_OFFLINE: 'APP_IS_OFFLINE',
    SETTINGS_UPDATE: 'SETTINGS_UPDATE',
    SETTINGS_INITIAL_LOAD: 'SETTINGS_INITIAL_LOAD',
    AUTH_ON_ERROR: 'AUTH_ON_ERROR',
    AUTH_ON_INIT: 'AUTH_ON_INIT',
    AUTH_ON_SUCCESS: 'AUTH_ON_SUCCESS',
    AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
    AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',

    SET_DASHBOARD_PAGE_HAS_RENDERED: 'SET_DASHBOARD_PAGE_HAS_RENDERED',
    SET_HAS_CACHED_REPO_ID_RETRIEVED_ONCE: 'SET_HAS_CACHED_REPO_ID_RETRIEVED_ONCE',
    SET_DASHBOARD_HAS_ALLOWED_TO_RERENDERED: 'SET_DASHBOARD_HAS_ALLOWED_TO_RERENDERED',

    UPDATE_APP_CONNECTION_STATUS_TO_ONLINE: 'UPDATE_APP_CONNECTION_STATUS_TO_ONLINE',
    UPDATE_APP_CONNECTION_STATUS_TO_OFFLINE: 'UPDATE_APP_CONNECTION_STATUS_TO_OFFLINE',

    SHOW_LOADING_BAR: 'SHOW_LOADING_BAR',
    HIDE_LOADING_BAR: 'HIDE_LOADING_BAR',

    GIVE_SEARCH_PRODUCT_REPOSITORIES_PERMISSION: 'GIVE_SEARCH_PRODUCT_REPOSITORIES_PERMISSION',
    REMOVE_SEARCH_PRODUCT_REPOSITORIES_PERMISSION: 'REMOVE_SEARCH_PRODUCT_REPOSITORIES_PERMISSION',

    GIVE_SEARCH_REPO_PRODUCTS_PERMISSION: 'GIVE_SEARCH_REPO_PRODUCTS_PERMISSION',
    REMOVE_SEARCH_REPO_PRODUCTS_PERMISSION: 'REMOVE_SEARCH_REPO_PRODUCTS_PERMISSION',

    GIVE_NEW_PRODUCT_CREATION_PERMISSION: 'GIVE_NEW_PRODUCT_CREATION_PERMISSION',
    REMOVE_NEW_PRODUCT_CREATION_PERMISSION: 'REMOVE_NEW_PRODUCT_CREATION_PERMISSION',

    GIVE_SETTINGS_PERMISSION: 'GIVE_SETTINGS_PERMISSION',
    REMOVE_SETTINGS_PERMISSION: 'REMOVE_SETTINGS_PERMISSION',

    GIVE_DASHBOARD_PERMISSION: 'GIVE_DASHBOARD_PERMISSION',
    REMOVE_DASHBOARD_PERMISSION: 'REMOVE_DASHBOARD_PERMISSION',

    GIVE_MY_PRODUCTS_PERMISSION: 'GIVE_MY_PRODUCTS_PERMISSION',
    REMOVE_MY_PRODUCTS_PERMISSION: 'REMOVE_MY_PRODUCTS_PERMISSION',

    GIVE_PROFILE_PERMISSION: 'GIVE_PROFILE_PERMISSION',
    REMOVE_PROFILE_PERMISSION: 'REMOVE_PROFILE_PERMISSION',

    GIVE_STATUS_PERMISSION: 'GIVE_STATUS_PERMISSION',
    REMOVE_STATUS_PERMISSION: 'REMOVE_STATUS_PERMISSION',

    GIVE_LOGOUT_PERMISSION: 'GIVE_LOGOUT_PERMISSION',
    REMOVE_LOGOUT_PERMISSION: 'REMOVE_LOGOUT_PERMISSION',

    RESET_OPTION_PERMISSIONS_TO_DEFAULT: 'RESET_OPTION_PERMISSIONS_TO_DEFAULT',

    SHOW_LOADING_SPINNER: 'SHOW_LOADING_SPINNER',
    HIDE_LOADING_SPINNER: 'HIDE_LOADING_SPINNER',

    SHOW_NETWORK_ISSUE_PANEL: 'SHOW_NETWORK_ISSUE_PANEL',
    HIDE_NETWORK_ISSUE_PANEL: 'HIDE_NETWORK_ISSUE_PANEL',

    SHOW_LOADING_PANEL: 'SHOW_LOADING_PANEL',
    HIDE_LOADING_PANEL: 'HIDE_LOADING_PANEL',

    SHOW_PERMISSION_REQUIRED_PANEL: 'SHOW_PERMISSION_REQUIRED_PANEL',
    HIDE_PERMISSION_REQUIRED_PANEL: 'HIDE_PERMISSION_REQUIRED_PANEL',

    CREATE_NEW_REDIRECT_REQUEST: 'CREATE_NEW_REDIRECT_REQUEST',
    CONSUME_REDIRECT_REQUEST_SUCCESSFULLY: 'CONSUME_REDIRECT_REQUEST_SUCCESSFULLY',

    UPDATE_SETTINGS: 'UPDATE_SETTINGS',
    LOAD_INITIAL_SETTINGS_FROM_CACHED: 'LOAD_INITIAL_SETTINGS_FROM_CACHED',

    UPDATE_SETTINGS_SHOW_NOTIFICATIONS: 'UPDATE_SETTINGS_SHOW_NOTIFICATIONS',
    UPDATE_SETTINGS_TOGGLE_SHOW_NOTIFICATIONS: 'UPDATE_SETTINGS_TOGGLE_SHOW_NOTIFICATIONS',

    UPDATE_SETTINGS_SIDE_BAR_VISIBILITY: 'UPDATE_SETTINGS_SIDE_BAR_VISIBILITY',
    UPDATE_SETTINGS_TOGGLE_SIDE_BAR_VISIBILITY: 'UPDATE_SETTINGS_TOGGLE_SIDE_BAR_VISIBILITY',

    UPDATE_SETTINGS_FOOTER_VISIBILITY: 'UPDATE_SETTINGS_FOOTER_VISIBILITY',
    UPDATE_SETTINGS_TOGGLE_FOOTER_VISIBILITY: 'UPDATE_SETTINGS_TOGGLE_FOOTER_VISIBILITY',

    UPDATE_SETTINGS_HEADER_VISIBILITY: 'UPDATE_SETTINGS_HEADER_VISIBILITY',
    UPDATE_SETTINGS_TOGGLE_HEADER_VISIBILITY: 'UPDATE_SETTINGS_TOGGLE_HEADER_VISIBILITY',

    UPDATE_SETTINGS_IMAGE_CONTAINER: 'UPDATE_SETTINGS_IMAGE_CONTAINER',
    UPDATE_SETTINGS_IMAGE_PADDING: 'UPDATE_SETTINGS_IMAGE_PADDING',
    UPDATE_SETTINGS_DARK_THEME: 'UPDATE_SETTINGS_DARK_THEME',
    UPDATE_SETTINGS_PLAY_SOUND: 'UPDATE_SETTINGS_PLAY_SOUND',

    UPDATE_CATEGORIES: 'UPDATE_CATEGORIES',
    UPDATE_CURRENCIES: 'UPDATE_CURRENCIES',
    UPDATE_SECRETKEYS: 'UPDATE_SECRETKEYS',
    UPDATE_COUNTRIES: 'UPDATE_COUNTRIES',
    SAVE_CATEGORIES: 'SAVE_CATEGORIES',
    SAVE_CURRENCIES: 'SAVE_CURRENCIES',
    SAVE_COUNTRIES: 'SAVE_COUNTRIES',
    UPDATE_SIUNITS: 'UPDATE_SIUNITS',
    SAVE_COUNTERS: 'SAVE_COUNTERS',
    SAVE_SIUNITS: 'SAVE_SIUNITS',

    SAVE_USER_DOCUMENT: 'SAVE_USER_DOCUMENT',
    UPDATE_USER_DOCUMENT: 'UPDATE_USER_DOCUMENT',
    SAVE_USER_NOTIFICATIONS: 'SAVE_USER_NOTIFICATIONS',

    RESET_ALL_STATES: 'RESET_ALL_STATES',

    SAVE_ALL_REPO_RELATED_FIELDS: 'SAVE_ALL_REPO_RELATED_FIELDS',

    SAVE_NEWLY_CREATE_PRODUCT_REPOSITORY: 'SAVE_NEWLY_CREATE_PRODUCT_REPOSITORY',

    UPDATE_PRODUCT_REPOSITORY: 'UPDATE_PRODUCT_REPOSITORY',

    PUSH_SEARCHED_ALL_PRODUCT_REPOSITORIES: 'PUSH_SEARCHED_ALL_PRODUCT_REPOSITORIES',
    RESET_STATE_OF_SEARCHED_PRODUCT_REPOSITORIES: 'RESET_STATE_OF_SEARCHED_PRODUCT_REPOSITORIES',

    SAVE_ALL_PAYMENTS_HISTORY: 'SAVE_ALL_PAYMENTS_HISTORY',

    SAVE_PRICE_PLANS_SAVING_PROCESS_SUCCESS: 'SAVE_PRICE_PLANS_SAVING_PROCESS_SUCCESS',

    SAVE_IC_STATUS_SUCCESS: 'SAVE_IC_STATUS_SUCCESS',

    PUSH_SEARCHED_MY_REPO_PRODUCTS_INSIDE_MY_REPOSITORIES: 'PUSH_SEARCHED_MY_REPO_PRODUCTS_INSIDE_MY_REPOSITORIES',
    PUSH_FETCHED_BY_IDS_MY_REPO_PRODUCTS_INSIDE_MY_REPOSITORIES: 'PUSH_FETCHED_BY_IDS_MY_REPO_PRODUCTS_INSIDE_MY_REPOSITORIES',
    RESET_STATE_OF_SEARCHED_MY_REPO_PRODUCTS_INSIDE_MY_REPOSITORY: 'RESET_STATE_OF_SEARCHED_MY_REPO_PRODUCTS_INSIDE_MY_REPOSITORY',

    PUSH_SEARCHED_OTHER_REPO_PRODUCTS_AS_GUEST: 'PUSH_SEARCHED_OTHER_REPO_PRODUCTS_AS_GUEST',
    RESET_STATE_OF_SEARCHED_OTHER_REPO_PRODUCTS_AS_GUEST: 'RESET_STATE_OF_SEARCHED_OTHER_REPO_PRODUCTS_AS_GUEST',

    SAVE_ALL_MY_REPO_PRODUCT_IDS: 'SAVE_ALL_MY_REPO_PRODUCT_IDS',
    REMOVE_REPO_PRODUCT_ID_TO_MY_REPOSITORY: 'REMOVE_REPO_PRODUCT_ID_TO_MY_REPOSITORY',
    INSERT_NEW_REPO_PRODUCT_ID_TO_MY_REPOSITORY: 'INSERT_NEW_REPO_PRODUCT_ID_TO_MY_REPOSITORY',

    SAVE_FETCHED_SINGLE_REPO_PRODUCT_DOCUMENT: 'SAVE_FETCHED_SINGLE_REPO_PRODUCT_DOCUMENT',
    REMOVE_FETCHED_SINGLE_REPO_PRODUCT_DOCUMENT: 'REMOVE_FETCHED_SINGLE_REPO_PRODUCT_DOCUMENT',

    SAVE_COOKIE_DETAILS: 'SAVE_COOKIE_DETAILS',
    UPDATE_COOKIE_DETAILS: 'UPDATE_COOKIE_DETAILS',
}