// CONSTANT VALUES

export const TYPES = {
    CURRENT_USER_FETCHING_INIT: 'CURRENT_USER_FETCHING_INIT',
    CURRENT_USER_FETCHED_FAILD: 'CURRENT_USER_FETCHED_FAILD',
    CURRENT_USER_FETCHED_SUCCESS: 'CURRENT_USER_FETCHED_SUCCESS',
    USER_FETCHING_BY_ID_INIT: 'USER_FETCHING_BY_ID_INIT',
    USER_FETCHED_BY_ID_FAILD: 'USER_FETCHED_BY_ID_FAILD',
    USER_FETCHED_BY_ID_SUCCESS: 'USER_FETCHED_BY_ID_SUCCESS',
    APP_IS_ONLINE: 'APP_IS_ONLINE',
    APP_IS_OFFLINE: 'APP_IS_OFFLINE',
    SETTINGS_UPDATE: 'SETTINGS_UPDATE',
    SETTINGS_INITIAL_LOAD: 'SETTINGS_INITIAL_LOAD',
    AUTH_ON_ERROR: 'AUTH_ON_ERROR',
    AUTH_ON_INIT: 'AUTH_ON_INIT',
    AUTH_ON_SUCCESS: 'AUTH_ON_SUCCESS',
    AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
    AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
}